### ISSUE TITLE
Limit for maximumFractionDigits option for decimal strings formatting

### ISSUE THREAD

**Issue by Yaffle** [tc39/proposal-intl-numberformat-v3#34]
Current limit is 20.

**Comment by sffc** [comment]
Do you have a suggestion about how high the limit should be raised?  What are the use cases you're looking at?

Due to implementation concerns, I think we should not go above 255 without a solid use case, and if we have a limit, perhaps something lower like 100 would be reasonable.

**Comment by sffc** [comment]
The main limitation with maximumFractionDigits is that it gives us a reasonable way to limit the maximum length of the string returned from Intl.NumberFormat.  If we were to raise the cap on maximumFractionDigits to something extremely large, it could be a security vulnerability, because it would become easy to make your computer run out of memory.

So in my opinion, it should be fairly harmless to increase the cap to, say, 100, 255, or perhaps a little bit larger if we have a clear use case, but increasing it to an extremely large number or Infinity voids the benefits that the cap serves in the first place.

**Comment by chicoxyzzy** [comment]
I never needed `maximumFractionDigits` more than 20 back when I was working in FinTech company, but I can imagine cases when limit increase could be useful.

https://brilliant.org/wiki/very-small-numbers/ - see Important "Very Small Numbers" part there

**Comment by sffc** [comment]
We decided in the 2021-07-01 meeting to decouple this issue from the NFv3 proposal. https://github.com/tc39/ecma402/issues/585
